Logging:
  default: INFO

General:
    Modus:         Box
    Delta_Time:    0.01
    End_Time:      10.0
    Randomseed:    -1
    Nevents:       1

Output:
    Output_Interval:  1.0
    Collisions:
        Format:  ["Binary"]
        Print_Start_End:    False
    Particles:
        Format:  ["Binary"]
        Only_Final:         No


Collision_Term:
    Collision_Criterion:      Stochastic
    # Value below choosen to optimze tests runtime, remove for production runs with deuterons
    Fixed_Min_Cell_Length:    2.5
    Included_2to2:            ["Elastic"]
    Multi_Particle_Reactions: ["Meson_3to1", "Deuteron_3to2"]
    Force_Decays_At_End:      False
    Strings:                  False


Modi:
    Box:
        Length: 10.0
        Temperature: 0.3
        Initial_Condition: "thermal momenta"
        Start_Time:    0.0

        Init_Multiplicities:
          2212:   50
          2112:   50
          -2212:  50
          -2112:  50
          333:    100
          331:    100
          223:    100
