Logging:
  default: INFO

General:
    Modus:         ListBox
    Delta_Time:    0.01
    End_Time:      10.0
    Randomseed:    -1
    Nevents:       3

Output:
    Output_Interval:  1.0
    Particles:
        Format:  ["Oscar2013"]
        Only_Final: No

Modi:
    ListBox:
        # If the build directory is not located in the smash directory anymore,
        # the absolute path specified below will not work anymore.
        # You can alternatively pass the path directly from the command line
        # with the "-c" command:
        # ./smash -i <path to config file> -c 'Modi: { List: { File_Directory: <path to file that is read in> } }
        # File_Directory: "../../smash-analysis/test/elastic_box"
        File_Directory: "../input/list"
        File_Prefix: "box_list"
        Shift_Id: 0
        Length: 10.0
